name: CI/CD Pipeline
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        context:
          - backend/init_db
          - backend/task_manager
          - backend/user_manager
          - frontend
        tags:
          - user/init_db:latest
          - user/task_manager:latest
          - user/user_manager:latest
          - user/frontend:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.4.0
        with:
          context: ${{ matrix.context }}
          push: false
          tags: ${{ matrix.tags }}
  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: linting
        uses: programmingwithalex/pylinter@main
        with:
          context: backend/user_manager
          python-root: '.'
          flake8-flags: ''
          mypy-flags: ''
          fail-on-isort: false











        
